services:
  - type: web
    name: vitaliti-oauth
    env: static
    staticPublishPath: ./public
    buildCommand: ""  # No build needed for static HTML
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /oauth-callback
        destination: /oauth-callback-enhanced.html
      - type: rewrite
        source: /oauth-callback-simple
        destination: /oauth-callback.html